spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reporting_service
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
kafka:
  bootstrapAddress: localhost:29092
server:
  port: 8082